name: '🚔'
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: gradle/wrapper-validation-action@v1.1.0
      - uses: actions/setup-java@v3.13.0
        with:
          java-version: 17
          distribution: 'temurin'
          check-latest: true
          cache: 'gradle'
      - run: ./gradlew --console plain --info --full-stacktrace check
