name: '🚔'
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: actions/setup-java@v3.6.0
        with:
          java-version: 17
          distribution: 'temurin'
          check-latest: true
          cache: 'maven'
      - run: mvn --batch-mode --show-version --errors test --file pom.xml
